import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Footer from "./components/footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const ClashDisplaySemibold = localFont({
  src: "./fonts/ClashDisplay-Semibold.woff",
  variable: "--font-clash-semi",
  weight: "100 900",
});
const Archivo = localFont({
  src: "./fonts/Archivo-Bold.woff",
  variable: "--font-archivo",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Yash Bharadwaj",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        {/* eslint-disable-next-line @next/next/no-page-custom-font*/}
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${ClashDisplaySemibold.variable} ${Archivo.variable} antialiased`}
      >
        {children}
        <footer>
          <Footer />
        </footer>
      </body>
    </html>
  );
}
